- .github/workflows/codeql-analysis.yml
Locate security vulnerabilities with CodeQL integrated with GitHub Actions
> Scan Security Vulnerabilities

- .github/CODEOWNERS
Updated reviewers for SchemaInventory.json.
> SchemaInventory.json  Reviewers

- Domains/Building/BuildingDataGroupBase/Released/BuildingDataGroupBase.01.00.01.ecschema.xml
- SchemaInventory.json
Publish WIP schema for OpenBuildings Connector
> Publish BuildingDataGroupBase.01.00.01

- tools/packages/packageSchema.yaml
> node version upgraded 

- Domains/Building/BuildingDataGroupBase/BuildingDataGroupBase.ecschema.xml
- SchemaInventory.json
Added Legacy Structural Properties for OpenBuildingsDesigner
> Added Legacy Structural Properies for OpenBuilding Designer

- Domains/Building/BuildingDataGroupBase/Released/BuildingDataGroupBase.01.00.02.ecschema.xml
- SchemaInventory.json
> Release BuildingDataGroupBase.01.00.02.ecschema.xml

- LICENSE.md
Header updated in license file
> Header updated in license file

- Domains/Fasteners/Fasteners.ecschema.xml
- Domains/FederatedDocumentStore/FederatedDocumentStore.ecschema.xml
- Domains/Rebar/Rebar.ecschema.xml
- Domains/StructuralDesign/Concrete/StructuralDesignConcrete.ecschema.xml
- Domains/StructuralMaterials/StructuralMaterials.ecschema.xml
Add ProductionStatus custom-attributes to unreleased Structural schemas.
> Add ProductionStatus custom-attributes to unreleased Structural schemas.

- .github/CODEOWNERS
Following updates are performed:
- Teams are updated with correct name. 
- @diegoalexdiaz told me to remove '@mrserg71'
> CODEOWNERS File Fixed

- tools/SchemaValidation/iModelEvolutionTests.yaml
This YAML provides the functionality to execute the iModelEvolutionTests with our PR's and finding the broken things earlier.
> Run iModelEvolutionTests for PR Validation

- Domains/2-DisciplinePhysical/StructuralMaterials/Released/StructuralMaterials.01.00.00.ecschema.xml
- Domains/2-DisciplinePhysical/StructuralMaterials/StructuralMaterials.ecschema.xml
- SchemaInventory.json
In production since a couple of years ago.
> Officially release StructuralMaterials 1.0.0.

- Domains/4-Application/ISM/IntegratedStructuralModel.ecschema.xml
- Domains/4-Application/ISM/Released/IntegratedStructuralModel.01.00.03.ecschema.xml
- SchemaInventory.json
Updated ISM schema with latest ISM Tendon API changes.
Additionally, fixed boolean parameters to match xsd, removed empty fields and updated used referenced schemas.
> ISM schema Tendon API update

- Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifUnits.01.00.04.ecschema.xml
- SchemaInventory.json
A small change to a kind of quantity is required in the CifUnits application schema. This PR would like to release this change officially.
> Release of CifUnits schema version 01.00.04

- package-lock.json
- package.json
- tools/SchemaValidation/imodel-native-tests.yaml
The PR contains following upgrades:
- Security issues fix
- Core build parameters update
- Fix for the native build failure
- Fix for "updateSchemaInventory tests" test failure during the build
> Fixed Security and Build Issues

- Domains/4-Application/Connectors/CivilInfrastructureFramework/CifGeometricRules.ecschema.xml
Updated CifGeometricRules.ecschema for removal of duplication of FilletRuleBaseAspect properties done by sub classes
> 1259630 Update CifGeometricRules.ecschema

- tools/SchemaValidation/imodel-native-tests.yaml
The timeout duration for the job that executes iModel evolution tests is updated.
> Updated timeout duration

- tools/SchemaValidation/imodel-native-tests.yaml
Limiting the number of threads for BB to 6.
> Specifying the number of threads for BB

- Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifUnits.01.00.05.ecschema.xml
- SchemaInventory.json
AREA and VOLUME KOQs now have US Survey presentation units
> Release updated CifUnits schema

- Domains/4-Application/Connectors/CivilInfrastructureFramework/CifHydraulicResults.ecschema.xml
- Domains/4-Application/Connectors/CivilInfrastructureFramework/CifSubsurface.ecschema.xml
- Domains/4-Application/Connectors/CivilInfrastructureFramework/CifUnits.ecschema.xml
Added new KOQs for dynamic display units
> PBI1224854

- package.json
> Fixed BIS Schemas Tools Test Runner 

- SchemaInventory.json
- Standard/Released/Units.01.00.08.ecschema.xml
This schema introduces a new unit - `Decanewton (daN)`
> Release of Units v01.00.08

- .github/CODEOWNERS
- Domains/4-Application/SynchroModeler/SynchroModeler.ecschema.xml
- SchemaInventory.json
Initial application specific schema for Synchro Modeler
> add initial SynchroModeler schema

- SchemaInventory.json
- Standard/ECDb/ECDbMap.remarks.md
- Standard/ECDb/ECDbMeta.remarks.md
- Standard/ECDb/Released/ECDbMap.02.00.03.ecschema.xml
- Standard/ECDb/Released/ECDbMeta.04.00.02.ecschema.xml
Added new version for upcoming ECDb profile version 4.0.0.5 which comes with a new ECDbMap schema.
> Add ECDbMap 02.00.03 and ECDbMeta 04.00.02 (View and CA support)

- Domains/4-Application/SynchroModeler/Released/SynchroModeler.01.00.00.ecschema.xml
- Domains/4-Application/SynchroModeler/SynchroModeler.ecschema.xml
- SchemaInventory.json
First release of SynchroModeler schema
> release SynchroModeler schema

- .github/CODEOWNERS
- Domains/3-DisciplineOther/Hydraulics/SewerHydraulicAnalysis.ecschema.xml
- Domains/3-DisciplineOther/Hydraulics/SewerHydraulicAnalysis.remarks.md
- SchemaInventory.json
The initial checkin for the hydraulic schema to be used in the booster app -
> Hydraulic schema - 

- tools/SchemaValidation/validateSchemas.yaml
Attempt number appended with artifacts name to avoid artifacts publishing issue while re-running a job.
> Attempt number appended with artifacts name

- Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifRail.01.00.09.ecschema.xml
- Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifUnits.01.00.07.ecschema.xml
- SchemaInventory.json
Release the CifUnits and CifRail schemas, which were modified to support the Cant Station Point properties.
> Update CifUnits schema version to 01.00.08 and CifRail schema version to 01.00.10

- Domains/3-DisciplineOther/Hydraulics/SewerHydraulicAnalysis.ecschema.xml
- Added new catchment schema as a basic analytical element
- added a relationship to relate the catchment schema to a node
- minor fix to the display label for the structure diameter.
> adding catchments to sewerhydraulics schema

- Domains/3-DisciplineOther/Hydraulics/SewerHydraulicAnalysis.ecschema.xml
adding two new informational elements:
1. to store calculation options
2.  to store design options
along with required enumerations
> Gvf calc options

- Domains/3-DisciplineOther/Hydraulics/SewerHydraulicAnalysis.ecschema.xml
1. added a new analytical element - pond as node with and elevation area curve property
2. added a new layer of abstraction BaseStructure so that all the nodes can share attributes....
> adding ponds to the schema

- Domains/3-DisciplineOther/Hydraulics/SewerHydraulicAnalysis.ecschema.xml
- add the new gutter element - has no attributes as of yet - just for directing carryover flow between catch basins
- added flag to rainfall event to include rainfall within the simulation
> gutters and tweak to rainfall events

- Domains/4-Application/Connectors/CivilInfrastructureFramework/CifBridge.ecschema.xml
- Domains/4-Application/Connectors/CivilInfrastructureFramework/CifGeometricRules.ecschema.xml
- Domains/4-Application/Connectors/CivilInfrastructureFramework/CifGeotechnical.ecschema.xml
- Domains/4-Application/Connectors/CivilInfrastructureFramework/CifHydraulicAnalysis.ecschema.xml
- Domains/4-Application/Connectors/CivilInfrastructureFramework/CifHydraulicResults.ecschema.xml
- Domains/4-Application/Connectors/CivilInfrastructureFramework/CifRail.ecschema.xml
- Domains/4-Application/Connectors/CivilInfrastructureFramework/CifRoads.ecschema.xml
- Domains/4-Application/Connectors/CivilInfrastructureFramework/CifSubsurface.ecschema.xml
- Domains/4-Application/Connectors/CivilInfrastructureFramework/CifSubsurfaceConflictAnalysis.ecschema.xml
- Domains/4-Application/Connectors/CivilInfrastructureFramework/CifSurvey.ecschema.xml
- Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifCommon.01.00.10.ecschema.xml
- SchemaInventory.json
To bring Speed Table information into iModel
> Release CifCommon schema which has Speed Section added on Alignment 

- Domains/4-Application/ISM/IntegratedStructuralModel.ecschema.xml
- Added a few more missing categories. 
- Removed a property from IsmLoadCombination.
> Add categories for a few more ECEntityClasses

- README.md
- tools/SchemaValidation/SchemaValidationRunner.js
Now a single schema can be validated using the bis rules validation.
> Fixed bis rule validation for single schema

- Domains/3-DisciplineOther/Hydraulics/PipeNetworkHydraulicAnalysis/PipeNetworkHydraulicAnalysis.eschema.xml
I created a relationship between the HydraulicMaterialAspect and the PipeElementType
> Creating relationship between the HydraulicMaterialAspect and the PipeElementType

- Domains/4-Application/OpenSite/OpenSite.ecschema.xml
- SchemaInventory.json
Added these properties to pond: 
- **Height**: Riser Top Elevation
- **TopHeight**: Dry Storage Height
- **WallSlope**: Side Slope
- **WallWidth**: Berm Width
- **Depth**: Riser Height
- **Size Pond**
- **Target surface**
- **Target volume**
> Add pond properties

- Domains/4-Application/OpenSite/OpenSiteDraft.ecschema.xml
- SchemaInventory.json
Add the "draft" schema for OpenSite that represent basic shapes for drafting purposes.
> Add the OpenSiteDraft schema

- Domains/3-DisciplineOther/Hydraulics/PipeNetworkHydraulicAnalysis/PipeNetworkHydraulicAnalysis.eschema.xml
added new aspect with the  IsAvailableForDesign Property to be applied to PipeElementType as well as other potential physical types to be used in the design process
> adding design aspect for physical element types

- LICENSE.md
- tools/packages/LICENSE.md
Change copyright to include 2025
> Change copyright to include 2025

- Domains/2-DisciplinePhysical/Civil/CivilPhysical/CivilPhysical.ecschema.xml
- Adds ```SurfaceMarking``` and ```SurfaceMarkingType``` to the ```CivilPhysical``` schema
> Add SurfaceMarking and SurfaceMarkingType

- Domains/4-Application/ISM/IntegratedStructuralModel.ecschema.xml
Added custom labels in relationships for source and target of relationships to be displayed for user.
> Add custom target and source relationship labels

- Domains/2-DisciplinePhysical/Civil/CivilPhysical/CivilPhysical.ecschema.xml
- Domains/2-DisciplinePhysical/Civil/CivilPhysical/Released/CivilPhysical.01.00.01.ecschema.xml
- SchemaInventory.json
- Adds ```SurfaceMarking``` class to the ```CivilPhysical``` schema for an incremental release to support "physical" parking lines in OpenSite+
> Release CivilPhysical 01.00.01

- Domains/4-Application/OpenSite/Released/OpenSiteDraft.01.00.01.ecschema.xml
- SchemaInventory.json
> [OpenSite] Release OpenSiteDraft 01.00.01

- Domains/4-Application/OpenSite/OpenSite.ecschema.xml
Add surface control to opensite schema
- SurfaceControl mixin for Layout and Shape Area
- SurfaceControlVertex
- SurfaceControlVertexRule
- SurfaceControlVertexDeltaRule: delta rule from start to end vertex
- SurfaceControlVertexSlopeRule: slope rule from start to end vertex
> [OpenSite] Add Surface Control to the OpenSite schema 

- Domains/3-DisciplineOther/Hydraulics/SewerHydraulicAnalysis.ecschema.xml
Added two new aspects for how to define the storage chamber
1.  DepthWidthStorageChamberDefinitionAspect which has an array of StorageChamberDepthWidthCurvePoint
2. VolumePerLengthStorageChamberDefinitionAspect which has an array of StorageChamberDepthUnitVolumeCurvePoint
> Storage chamber 2

- Domains/4-Application/OpenSite/OpenSite.ecschema.xml
- Domains/4-Application/OpenSite/Released/OpenSite.01.00.05.ecschema.xml
- SchemaInventory.json
Adds surface control, linear/top surface, and driveway transition classes, as well as related relationships.
> Release OpenSite 01.00.05 schema

- Domains/4-Application/OpenSite/OpenSite.ecschema.xml
- Adds curb type to schema with set of properties needed to calculate geometry
> Add Curb Types to OpenSite+ Schema

- Domains/3-DisciplineOther/Hydraulics/Released/SewerHydraulicAnalysis.01.00.02.ecschema.xml
- Domains/3-DisciplineOther/Hydraulics/SewerHydraulicAnalysis.ecschema.xml
- SchemaInventory.json
releasing version 2 of sewerhydraulicanalysis with storage chambers, and improved catchments
> releasing version 1.0.2 of sewerhydraulicanalysis

- Domains/4-Application/Connectors/CivilInfrastructureFramework/CifBridge.ecschema.xml
- Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifBridge.01.00.15.ecschema.xml
- SchemaInventory.json
- changed KindOfQuanitity for Weight props to MASS
- moved Station prop for Caps to a parent class
> releasing CifBridge schema version 01.00.15

- Domains/4-Application/OpenSite/Released/OpenSite.01.00.08.ecschema.xml
- SchemaInventory.json
* Releases version 01.00.08, containing CurbTypes and SidewalkFins
> Release OpenSite 01.00.08

- Domains/2-DisciplinePhysical/Civil/CivilPhysical/CivilPhysical.ecschema.xml
- Domains/4-Application/OpenSite/OpenSite.ecschema.xml
Add classes in both OpenSite schema and CivilPhysical for retaining walls.
> Add Retaining wall

- Domains/4-Application/OpenSite/Released/OpenSite.01.00.09.ecschema.xml
- SchemaInventory.json
Releases version 01.00.09, containing SurfaceControlLine, SurfaceControlOptionsAspect and more properties on SurfaceControlVertex
> Release OpenSite 01.00.09

- Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifHydraulicAnalysis.01.00.09.ecschema.xml
- SchemaInventory.json
Release CifHydraulicAnalysis schema to correctly display the size property of conduits
> Release CifHydraulicAnalysis schema to correctly display the size property of conduits

- Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifBridge.01.00.16.ecschema.xml
- SchemaInventory.json
For Bug1633869, making Offset From SupportLine property visible
> Release CifBridge schema to make Offset From SupportLine property visible in iModel

- Domains/4-Application/Connectors/CivilInfrastructureFramework/CifCommon.ecschema.xml
- Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifCommon.01.00.14.ecschema.xml
- SchemaInventory.json
Release CifCommon schema to support the Civil Properties of Plan Named Boundary in iModel
> Release CifCommon schema to support the Civil Properties of Plan Named Boundary in iModel

- Domains/4-Application/Connectors/CivilInfrastructureFramework/CifBridge.ecschema.xml
- Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifBridge.01.00.17.ecschema.xml
- SchemaInventory.json
changed the properties for Pile. Changed the Category field from BridgeModelerAttributes_Pier to 
PileProperties_Pile which is the correct category for Piles
>  schema Pile properties category change

- Domains/4-Application/ISM/IntegratedStructuralModel.ecschema.xml
Change derived SpatialElement to Spatiallocationelement
> Change ISM SpatialElement to SpatialLocationElement

- Domains/4-Application/OpenSite/OpenSite.ecschema.xml
Add the option for pad areas to disable parking inside of it. 
This would allow the creation of custom islands.
> [OpenSite+] Add parking allowed for pad areas

- Domains/4-Application/OpenSite/OpenSite.ecschema.xml
Deprecate the curb height property.
> [OpenSite+] Deprecate the curb height property

- Domains/4-Application/OpenSite/OpenSite.ecschema.xml
Added 3 relationships to symbolize parking lots through classification
> [OpenSite+] Add 3 relationships for parking symbology

- Domains/2-DisciplinePhysical/Civil/SpatialComposition/CivilSpatial/CivilSpatial.ecschema.xml
- Domains/4-Application/OpenSite/OpenSite.ecschema.xml
- Added `LayoutParcelingArea` class to the OpenSite schema with 7 properties.
- Added `Parcel` class to the CivilSpatial schema
> [OpenSite+] Add parceling

- Domains/2-DisciplinePhysical/Civil/SpatialComposition/CivilSpatial/CivilSpatial.ecschema.xml
- Domains/2-DisciplinePhysical/Civil/SpatialComposition/CivilSpatial/Released/CivilSpatial.01.00.01.ecschema.xml
- SchemaInventory.json
Release CivilSpatial 1.0.1 containing an added Parcel class.
> [CivilSpatial] Release CivilSpatial 1.0.1
