Domains/Building/BuildingDataGroupBase/BuildingDataGroupBase.ecschema.xml
SchemaInventory.json

OpenBuildings products refer to "Part" instances from every element. "Parts" define resymbolization behavior and are stored in the workspace. By Persisting the Parts in the itwin we can monitor changes and update resymbolization when needed.

Add OpenBuildings Part Class

---

Domains/Civil/Connectors/ConceptStation/CSSegments.ecschema.xml
Domains/Civil/Connectors/ConceptStation/CSSegments.remarks.md
Domains/Civil/Connectors/ConceptStation/CSUnits.ecschema.xml
Domains/Civil/Connectors/ConceptStation/CSUnits.remarks.md
SchemaInventory.json

This PR introduces a new pair of application schemas for the ConceptStation Connector: CSSegments and CSUnits. CSUnits provides schema for application-specific units used by the ConceptStation Connector. CSSegments provides application-specific support for ConceptStation "segments" in the iModel, along with the application-specific ConceptStation pay item data.

Concept station segment assemblies

---

Domains/Core/BisCore.remarks.md
README.md
docs/schema-cmap-class-style-guide.md
docs/writing-schema-documentation.md
tools/packages/README.md.template
tools/packages/package.json.template

The PR contains following updates:
- Links now point to itwinjs.org instead of imodeljs.org.
- Some repository and other keywords are also updated

Documentation upgrade with respect to iTwin.js

---

package-lock.json
package.json
tools/MarkdownGeneration/generate-docs.yaml
tools/SchemaValidation/validateSchemas.yaml
tools/packages/packageSchema.yaml
tools/testRunner.yaml

Consumed tools are now upgraded to iTwin packages version 3.0.2. Also, node version is upgraded for the YAML's.

Moving on iTwin 3.0.2

---

package-lock.json
package.json
tools/SchemaValidation/iModelSchemaValidationRunner.js

Proper error message is now defined. Also '@bentley/bentleyjs-core' was not able to provide the error trace so moved on the newer package '@itwin/core-bentley'

Schema Import Error and Trace Fix

---

tools/MarkdownGeneration/generate-docs.yaml

Right now, this validation part consumes the template from 'io-fix-build-to-yaml'.

Moving 'Validate Docs' job to consume template from master branch of itwinjs-core

---

tools/MarkdownGeneration/generate-docs.yaml

When artifacts are generated with manual builds, this change will help to also validate them.

Allow executing validation part for manual builds

---

Domains/4-Application/Connectors/CivilInfrastructureFramework/CifCommon.ecschema.xml

In the CifCommon schema, I deprecated and hid the MeshSurfaceEntity_StartStation and MeshSurfaceEntity_EndStation properties because they were defined as strings instead of doubles. I also added 2 new replacement properties with the correct (numeric) type and unit: MeshSurfaceEntity_StartStationNumeric and MeshSurfaceEntity_EndStationNumeric.

Civil Connector 10.11 support additional fix

---

SchemaInventory.json
tools/packages/packageSchema.yaml

Path of the schema is corrected to fix BIS-Schema-Packaging build.
The package generation task will now be executed with the PR build to validate this stuff but will not publish the packages as build artifacts until its executing on master branch.

Breaking Changes Fixed and Allow Executing Validation

---

tools/MarkdownGeneration/generate-docs.yaml

The docs-build template in itwinjs-core changed due to a refactor. This PR updates the pipeline consuming that template to reflect those changes. 
Stages were added to this pipeline in order to enforce the sequential run order of the pipeline's jobs. Because we cannot override the dependencies or conditions of the docs-build job template, we add it to it's own stage in order to set dependencies/conditions at that level.

Fix generate docs pipeline

---

Domains/4-Application/Connectors/CivilInfrastructureFramework/CifBridge.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/CifCommon.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/CifGeometricRules.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/CifHydraulicAnalysis.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/CifHydraulicResults.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/CifRail.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/CifSubsurface.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/CifSubsurfaceConflictAnalysis.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifBridge.01.00.08.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifCommon.01.00.05.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifGeometricRules.01.00.03.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifHydraulicAnalysis.01.00.05.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifHydraulicResults.01.00.05.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifRail.01.00.04.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifSubsurface.01.00.05.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifSubsurfaceConflictAnalysis.01.00.05.ecschema.xml
SchemaInventory.json

Release of new versions of the following Civil Connector application schemas:
CifBridge (01.00.08)
CifCommon (01.00.05)
CifGeometricRules (01.00.03)
CifHydraulicAnalysis (01.00.05)
CifHydraulicResults (01.00.05)
CifRail (01.00.04)
CifSubsurface (01.00.05)
CifSubsurfaceConflictAnalysis (01.00.05)

Release of Civil Connector application schemas (existing schemas, but new versions)

---

Domains/3-DisciplineOther/StructuralAnalysis/StructuralAnalysis.ecschema.xml
SchemaInventory.json

01.00.02 was never released.
01.00.02 dev schema version was updated to 01.00.03 unintentionally. This PR just reverts the version back to unreleased 01.00.02

Revert StructuralAnalysis version number back to 01.00.02

---

Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifBridge.01.00.10.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifCommon.01.00.06.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifGeometricRules.01.00.04.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifHydraulicAnalysis.01.00.06.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifHydraulicResults.01.00.06.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifRail.01.00.05.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifRoads.01.00.03.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifSubsurface.01.00.07.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifSubsurfaceConflictAnalysis.01.00.06.ecschema.xml
SchemaInventory.json

Release of Civil Connector application schema updates to support OpenX 2023 product schema changes. The actual schema changes were added to the WIP schema versions through the following 2 PRs:
https://github.com/iTwin/bis-schemas/pull/230
https://github.com/iTwin/bis-schemas/pull/232

Release of Civil Connector application schema updates for OpenX 2023.

---

Domains/1-Common/ClassificationSystems/ClassificationSystems.remarks.md
Domains/1-Common/DistributionSystems/DistributionSystems.remarks.md
Domains/1-Common/LinearReferencing/LinearReferencing.remarks.md
Domains/1-Common/Profiles/Profiles.remarks.md
Domains/1-Common/SpatialComposition/SpatialComposition.remarks.md
Domains/2-DisciplinePhysical/Building/BuildingSpatial/BuildingSpatial.remarks.md
Domains/2-DisciplinePhysical/Civil/BridgePhysical/BridgePhysical.remarks.md
Domains/2-DisciplinePhysical/Civil/RoadRailAlignment/RoadRailAlignment.remarks.md
Domains/2-DisciplinePhysical/Civil/SpatialComposition/BridgeSpatial/BridgeSpatial.remarks.md
Domains/2-DisciplinePhysical/Civil/SpatialComposition/RoadSpatial/RoadSpatial.remarks.md
Domains/2-DisciplinePhysical/Earthwork/Earthwork.remarks.md
Domains/2-DisciplinePhysical/Fasteners/Fasteners.remarks.md
Standard/BisCustomAttributes.remarks.md
Standard/CoreCustomAttributes.remarks.md

Several schema remarks contained sections at the wrong md level, leading to those sections to be left out from the final schema documentation.
Updated links to IFC docs now that their final 4.3 version is released.

Fixes to md level formatting in remarks.

---

tools/SchemaValidation/imodel-native-tests.yaml

The pipeline is currently failing as the default value of this parameter was removed from the template.

Fix iModelNativeTests Pipeline

---

tools/SchemaValidation/imodel-native-tests.yaml
tools/testRunner.yaml

This PR contains following changes:
- The core-build template should be using the `master` branch.
- `BIS Schemas Tools Test` pipeline execute the tooling tests and it should not be executed with irrelevant changes.

iModelNativeTests pipeline fix and path filters

---

tools/SchemaValidation/imodel-native-tests.yaml

The machines having python 3.12 show this issue as this module was deprecated.

Fixed `ModuleNotFoundError: No module named 'distutils'` Issue

---

Domains/4-Application/Connectors/Connector.ecschema.xml
Domains/4-Application/Connectors/Released/Connector.01.01.00.ecschema.xml
README.md
SchemaInventory.json
tools/SchemaValidation/validateSchemas.yaml

In the final step of updating a model, the connector now detects and deletes rule violations involving elements that a) were skipped by a prior update and b) that were caused by external elements that have since been deleted. To support this, I added the "Required" property to connector:RuleViolation. See the description in the schema.

Adding the "Required" property to connector:RuleViolation

---

Domains/4-Application/Connectors/CivilInfrastructureFramework/CifRail.ecschema.xml
Domains/4-Application/Connectors/CivilInfrastructureFramework/CifUnits.ecschema.xml

To correctly show the Cant Station Points properties in iModel, modifications in CifUnits and CifRail schemas are added.

Modifications to support Cant Station Points properties with appropriate units

---

Domains/4-Application/ISM/IntegratedStructuralModel.ecschema.xml

Changed IsmPipingNode class property name from incorrect `Type` to `JointType`.

Change IsmPipingNode class property name

---

Domains/3-DisciplineOther/Hydraulics/SewerHydraulicAnalysis.ecschema.xml

Adding two new Definition elements to allow users to define which shapes and materials to use in the automated design.
- Pipe Size Set - A set of pipe sizes with the same shape and material.... and owns a set of Pipe Sizes
- Pipe Size - gives a selectable unique id for each pipe size along with an initial roughness value...
-  Each pipe size points to a PipeShapeAspect which already exists

adding schema for design pipe sizes

---

Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifBridge.01.00.13.ecschema.xml
SchemaInventory.json

Release CifBridge schema which will hide the Build Order fields in iModel

Release CifBridge schema which will hide the Build Order fields in iModel for all OBM objects

---

Domains/4-Application/ISM/IntegratedStructuralModel.ecschema.xml

- Added `PropertyCategory` elements for multiple ECClasses (mainly rebar elements)
- Updated multiple incorrect displayedLabels in ECProperties
- Updated multiple incorrect/missing kindOfQuantity values in ECProperties
- Added 2 missing properties to IsmAreaSurfaceRebar ECClass
- Updated `typeName` of `AutoBarCount` property from `double` to `int` in `IsmParallelRebar` and `IsmPerpendicularRebar` ECClasses 
- Fixed a few typos (`ECStructClass` misspelled as `ECStrucClass` and `ECClass.modifier` misspelled as `ECClass.modified`)
- Corrected ECClass modifiers for several classes
- Fixed an ECProperty using the incorrect ECEnumeration

Add categories for rebar ECClasses to ISM IntegratedStructuralModel schema + various minor fixes

---

Domains/4-Application/ISM/IntegratedStructuralModel.ecschema.xml

Updated ISM IntegratedStructuralModel schema:
- Added PropertyCategories for a lot of ECEntityClasses
- Added references to Units and Formats schemas
- Updated kindOfQuantity for multiple ECProperties
- Updated displayLabels for multiple ECProperties
- Updated BaseClass of IsmCurveForceMemberLoad ECEntityClass
- Added IsmFixityDirection ECEnumeration
- Fixed incorrect ECProperty name: OutPlaneStressOuttensificationFactor -> OutPlaneStressIntensificationFactor
- Changed precision for FrictionCoefficient ECProperties on PipingSupports: 2DP -> 3DP

Add categories for ECClasses + various small fixes

---

Domains/4-Application/ISM/IntegratedStructuralModel.ecschema.xml

- Removed IsmNodeLink fixities category
- This is because fixity values need calculatedProperties. Category will be created inside of the ruleset because of that

Removed IsmNodeLink fixities category

---

Domains/3-DisciplineOther/Hydraulics/SewerHydraulicAnalysis.ecschema.xml

Added three new aspects
- NodeDesignConstraintsAspect
- PipeDesignConstraintAspect
- InletDesignConstraintAspect
Add a new informational entity class "GlobablDesignConstraints" which references the above three aspects
Added design attributes to GravityStructure, Pipe and Inlet.   If the user chooses to override the global constraints will bind to relevant aspect above (eg Pipe => PipeDesignConstraintAspect)

Adding Design properties to sewer hydraulic schema

---

Domains/3-DisciplineOther/Hydraulics/SewerHydraulicAnalysis.ecschema.xml

1. I made a pass on diameters and changed the koq to LENGTH_SHORT where appropriate - structure diameter is usually presented in the larger units for example
2.  There were a couple of spots using the wrongs units , or using the AECU units instead of the rru
3. Add a enum to the rainfalleventset to store the type of rainfall data associated with it
4. refactor the CalcOptions so they are more like Design constraints...
There is now a CalculationOptions element with an enum for engine type, and based on the engine type will select the appropriate calc options aspect

Adding SWMM calculation options - along with some minor unit tweaks

---

tools/SchemaValidation/iModelEvolutionTests.yaml
tools/SchemaValidation/imodel-native-tests.yaml

With respect to the following changes on core side: https://github.com/iTwin/itwinjs-core/pull/7379 updating the node version.
Additionally, we have fixed some path filters for the build execution.

Use Node 22.x for iTwinjsCore build

---

Domains/3-DisciplineOther/Hydraulics/SewerHydraulicAnalysis.ecschema.xml

1. Add Headloss fields to the the GravityStructure  along with associated aspects
2. Catchments - I added a number of aspects that can be mixed and matched based on the desired configuration
CatchmentTimeOfConcentrationAspect
CatchmentAreaDefinitionSelectorAspect
CatchmentAreaDefinitionAspect
CatchmentSimpleAreaDefinitionAspect
CatchmentRationalSimpleAreaAspect
CatchmentRationalComplexAreaDefinitionAspect
EpaSWMMRunoffMethodAreaAspect
CatchmentScsUhSimpleAreaDefinitionAspect
CatchmentScsUhComplexAreaDefinitionAspect
CatchmentInfiltrationMethodAspect
CatchmentScsCnInfiltrationMethodAspect
CatchmentHortonInfiltrationMethodAspect
CatchmentGreenAndAmptInfiltrationMethodAspect
3. Added GlobalHydraulicModelSettings entity to store the project configuration data

Adding Catchment Data and Headloss schema

---

Domains/4-Application/OpenSite/OpenSite.ecschema.xml
SchemaInventory.json

Changes following properties from using KoQ `rru:LENGTH` to `rru:LENGTH_SHORT`:
- CenterlinePathEdge.SurfaceDepth
- ShapedArea.SurfaceDepth
- GradingArea.SurfaceDepth
- LayoutParkingArea.SurfaceDepthParkingLot
- LayoutParkingArea.SurfaceDepthParkingSpaces
- EdgeOnSideParkingAspect.OnSideParkingSurfaceDepth
- GradingArea.Topsoil
- ShapedArea.Topsoil

Use rru:LENGTH_SHORT KoQ in OpenSite properties

---

Domains/1-Common/AecValueDefinitions/AecValueDefinitions.ecschema.xml
Domains/2-DisciplinePhysical/Piping/PipeworkPhysical.ecschema.xml

`AecValueDefinitions` and `PipeworkPhysical` do not use anything new in working version (1.0.4) of `AecUnits`. `PipeworkPhysical` will release is soon - no need to force `AecUnits` release.

Use latest released AecUnits Schema in AecValueDefinitions and PipeworkPhysical

---

Domains/3-DisciplineOther/Hydraulics/SewerHydraulicAnalysis.ecschema.xml

I will hold off on the units change....
1. Removed the PipeSet stuff as has been replaced
2.  Add a relationship to associate the outfall with node design constraints

Outfall Design Constraints - Removing old pipe library

---

Domains/4-Application/OpenSite/OpenSiteDraft.ecschema.xml
tools/SchemaValidation/iModelSchemaValidationRunner.js

The OpenSiteDraft schema filename is **OpenSiteDraft**.ecschema.xml but the XML has `schemaName="OpenSiteDrafts"` that is causing the following issue:
```
An error occurred during validation: ENOENT: no such file or directory, lstat 'C:\Users\VSSADM~1\AppData\Local\Temp\SchemaValidation\Briefcases\validation\testimodel\exported\OpenSiteDraft.01.00.00.ecschema.xml'
```

Fixed bug in WIP schema validation and updated OpenSiteDraft schema name

---

Domains/3-DisciplineOther/Hydraulics/SewerHydraulicAnalysis.ecschema.xml

1. fixed the properties on the curb inlet
2. add a channel element along with channel shape aspects
3. Added headwalls -  
this includes an enumeration with wall the InletControl coefficients
along with various aspects that describe the different ways headwalls can be treated: Outfall, PondInflow, PondOutflow, Transition

Channels and end walls

---

Domains/2-DisciplinePhysical/Civil/RoadRailUnits/RoadRailUnits.ecschema.xml
Domains/3-DisciplineOther/Hydraulics/SewerHydraulicAnalysis.ecschema.xml

1. fixed the length_short formatter to use mm and inches
2.  added an infiltration_intensity formatter for rainfall intensity
3.  added a side slope formatter which uses the inverted slope unit - for the side slopes trapezoidal channels along with some coming attributes associated with storage

hydraulic unit fix ups

---

Domains/2-DisciplinePhysical/Civil/RoadRailAlignment/RoadRailAlignment.remarks.md

Fix links that point to the itwinjs docs. (It was returning 404s)
The URLs contained the old package name 'geometry-core' which has now been replaced by 'core-geometry'.
This is simple bookkeeping. I did not look at other files.

Fix links in RoadRailAlignment.remarks.md

---

Domains/2-DisciplinePhysical/Civil/RoadRailUnits/RoadRailUnits.ecschema.xml
Domains/3-DisciplineOther/Hydraulics/PipeNetworkHydraulicAnalysis/PipeNetworkHydraulicAnalysis.ecschema.xml
Domains/3-DisciplineOther/Hydraulics/SewerHydraulicAnalysis.ecschema.xml

- Added a new RATIONAL_COEFFICIENT, MANNINGS_N, and HAZEN_WILLIAMS_C  koqs  to handle to formatting for these type of quantities
Let me know if I need to adjust anything

Adding new KOQs for unitless coefficient

---

Domains/4-Application/OpenSite/OpenSite.ecschema.xml

- In OpenSite+, we were planning to use the ElementDrivesElement relationship when creating Spatial areas (as outputs) from our Authoring elements (inputs) during site layout to link the related elements in different models:
- The ElementDrivesElement relationship will be used in other places in our application (ex. Drainage), so a sub-class would help clarify the nature of the relationship for each instance
- This PR adds a "AuthoringElementDrivesPlanElement" relationship to meet these needs

Add "AuthoringElementDrivesPlanElement" schema relationship

---

Domains/0-Core/BisCore.ecschema.xml

- AnnotationTextStyle not deprecated.
- Deprecate AnnotationTextStyle.Data.
- New AnnotationTextStyle.Settings property (Json-based).
- New TextAnnotationData properties (Json-based) on TextAnnotation2d and 3d.
Captured both the tweaks to deprecations as well as the new properties into a single PR rather than two as originally mentioned in the BWG meeting, in order to link them via deprecation descriptions.
These changes are meant to be included in the upcoming release of BisCore (01.00.17), which is planned to be deployed by iTwin.js-core 5.

Reflect decisions from 2/7/2025 BWG meeting.

---

Domains/4-Application/OpenSite/OpenSite.ecschema.xml
SchemaInventory.json

Add ElementDrivesElement subclasses for cases where an dependent element is defined along a linear source element

Add ElementDrivesElement subclasses for cases where an dependent element is defined along a linear source element

---

Domains/2-DisciplinePhysical/Civil/RoadRailUnits/Released/RoadRailUnits.01.00.03.ecschema.xml
Domains/3-DisciplineOther/Hydraulics/Released/SewerHydraulicAnalysis.01.00.01.ecschema.xml
Domains/3-DisciplineOther/Hydraulics/SewerHydraulicAnalysis.ecschema.xml
SchemaInventory.json
pnpm-lock.yaml

Change the hydraulic schema so that we go back to depending on released schema versions of NetworkTopology and StormSewerPhysical. There are no changes in the newer dev schemas anyway

Change the hydraulic schema so that we go back to depending on released schemas

---

Domains/4-Application/ISM/IntegratedStructuralModel.ecschema.xml

Changed from using default N/m^2 to kN/m^2 unit.

Use a different unit system for linear springs

---

Domains/4-Application/OpenSite/OpenSite.ecschema.xml

`PropertyArea` class is being changed to only represent "Grading Limits" and no longer have control over parking/building setbacks. Setback control will be implemented via different means in the future.
- Update class labels
- Deprecate and hide `PropertyEdge.ParkingSetback` and `PropertyEdge.BuildingSetback` properties

[OpenSite] Update class labels and deprecate PropertyEdge setback properties

---

Domains/4-Application/OpenSite/OpenSite.ecschema.xml

Adds the DrivewayTransition entity class (owned by the DrivewayMidVertex) with offset and radius properties. These properties on the DrivewayMidVertex have been marked as deprecated.

[OpenSite] Add DrivewayTransitions; deprecate old transition properties on DrivewayMidVertex

---

Domains/4-Application/OpenSite/OpenSite.ecschema.xml

- Add Surface Control Low Point to the OpenSite schema
- Add `SurfaceControlLowPoint` and `SurfaceControlLowPointRule`
- Fix multiplicity of `SurfaceControlVertexRuleStartsAtVertex` and `SurfaceControlVertexRuleEndsAtVertex`
- Remove `SurfaceControlVertex` modifier so that `SurfaceControlLowPointRule` can have it as BaseClass

[OpenSite] Add Surface Control Low Point to the OpenSite schema

---

Domains/4-Application/Connectors/CivilInfrastructureFramework/Released/CifCommon.01.00.13.ecschema.xml
SchemaInventory.json

Added derived classes for MeshSurfaceEntityBaseAspect, which is a copy of MeshSurfaceEntityAspect, but it will give us the flexibility of showing and hiding properties as per the requirement of the element

Release CifCommon schema to support various derived classes of Mesh

---

Domains/4-Application/OpenSite/OpenSite.ecschema.xml

- Add `SurfaceSlopedControlVertex` and `SurfaceSlopedDirectionControlVertex`
- Add `ControlLineEdge`, `SurfaceControlLine` and correpsonding relationships
- Add `SurfaceControlOptionsAspect` and `SurfaceControlOwnsOpstionsAspect`
- Deprecate `SurfaceControlLowPoint`, `SurfaceControlLowPointRule`, `SurfaceControlLowPointRuleGroupsVertices` and `SurfaceControlOwnsVertices`

[OpenSite] Add Sloped Control Vertex and Control Line to the OpenSite schema

---

Domains/4-Application/OpenSite/OpenSite.ecschema.xml

- Add `ISurfaceControlElement` mixin and `SurfaceControlOwnsControlElements` rel, which applies to all control objects and rules
- Removed `SurfaceControlOwnsControlObjects` (they are added in last PR, not released yet so we just delete)
- Deprecated `SurfaceControlOwnsRules`
- Combine all Control Vertex elements into `SurfaceControlVertex`
- Delete `SurfaceSlopedControlVertex` and `SurfaceSlopedDirectionControlVertex` and migrated properties (they are added in last PR, not released yet so we just delete)
- Add `ControlVertexType` enum for `vertexType` property of `SurfaceControlVertex`
- Add `SurfaceControlStrokeOptions` struct property for `SurfaceControlVertexRule` and `SurfaceControlLine`

[OpenSite] Update Control Vertex for OpenSite schema

---

Domains/2-DisciplinePhysical/Civil/CivilPhysical/CivilPhysical.ecschema.xml
Domains/4-Application/OpenSite/OpenSite.ecschema.xml

This relationship will be used to control the hierarchy shown in classification tree.
We are testing it in OpenSite+, but it is intended to be common later.

Add CategorySymbolizesClassification to OpenSite schema

---

ignoreSchemaList.json
package.json
tools/SchemaValidation/iModelSchemaValidation.js
tools/SchemaValidation/iModelSchemaValidationRunner.js
tools/SchemaValidation/test/assets/1/Released/SchemaA.01.00.00.ecschema.xml
tools/SchemaValidation/test/assets/1/Released/SchemaA.01.00.01.ecschema.xml
tools/SchemaValidation/test/assets/1/Released/SchemaA.01.00.02.ecschema.xml
tools/SchemaValidation/test/assets/1/Released/SchemaA.02.00.00.ecschema.xml
tools/SchemaValidation/test/assets/1/Released/SchemaA.02.00.01.ecschema.xml
tools/SchemaValidation/test/assets/1/Released/SchemaA.02.00.02.ecschema.xml
tools/SchemaValidation/test/assets/1/Released/SchemaB.01.00.00.ecschema.xml
tools/SchemaValidation/test/assets/1/Released/SchemaB.02.00.00.ecschema.xml
tools/SchemaValidation/test/assets/1/Released/SchemaB.02.01.00.ecschema.xml
tools/SchemaValidation/test/assets/1/Released/SchemaB.03.00.00.ecschema.xml
tools/SchemaValidation/test/assets/1/SchemaB.ecschema.xml
tools/SchemaValidation/test/assets/2/Released/SchemaC.01.00.00.ecschema.xml
tools/SchemaValidation/test/assets/2/Released/SchemaD.01.00.00.ecschema.xml
tools/SchemaValidation/test/assets/2/Released/SchemaD.01.01.00.ecschema.xml
tools/SchemaValidation/test/assets/2/Released/SchemaD.02.00.00.ecschema.xml
tools/SchemaValidation/test/assets/2/Released/SchemaE.01.00.00.ecschema.xml
tools/SchemaValidation/test/assets/2/SchemaD.ecschema.xml
tools/SchemaValidation/test/schemaUpgrade.test.js
tools/testRunner.yaml

The schema upgrade testing should be performed for the same read versions of a schema.

Schema upgrade tests should consider same read version

---

Domains/4-Application/DrawingProduction/SheetNumbering.ecschema.xml
Domains/4-Application/DrawingProduction/SheetNumberingViews.ecschema.xml
SchemaInventory.json

Added ECView gathering all calculated SheeNumber Info related to Sheet.  This is intended to work with fields and provide a list of properties that should "appear to the user" as a properties of a sheet.
Questions:
1. When dealing with referenced schemas, how much does the path version matter, specifically with BisCore?  Is there a possibility of a lower patch version of a schema getting imported because of a referenced schema?
2. (Maybe more of a BWG question) Should the Sheet Id be a property on the SheetNumberInfo?  Would that make a better ECInstanceId?  Should there be some sort of relationship between a Sheet and the SheetNumberingInfo classes?
After this, we will quickly follow this PR with another looking to release this schema.

Added SheetNumbering ECView to the SheetNumdering Schema
